[build-system]
requires = ["setuptools >= 41.0.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ["py310", "py310", "py311", "py313"]

[tool.isort]
profile = "black"
skip_gitignore = true
line_length = 100
treat_comments_as_code = ["# %%"]
