name: test
on: push
jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
    - uses: lumicks/boilerplate/.github/actions/checkout@main
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: pip install .[testing] pytest-xdist
    - name: pytest
      run: pytest -n auto
